sudo: required
language: python
services:
- docker
env:
  global:
  - DOCKER_IMAGE=leon11sj/data-storage-microservice:version-0.1.0-$TRAVIS_JOB_NUMBER
  - secure: 52bAf8mjXBGBQEYBZ0Fn37XB3Pm0/0Td1FSiDr3k+7hIsfYkAhs07ZidkSNiTg17Pbd1nX/OcUrbeTQlMwt5hOMwEC+K1uj5mMy+k98m+0uGljgdoZaQyQNZpKAi2r+ofsSBSLGHtQYW1+siriK/XMJSAhxJM3Kw8XANyNJmWSPJLpUjqWmk1QYdA/fUEtYRTXMsMAnBAeXxphsQwzzjP+nyTy6H7Hhcb0G9wqa4uYQsyJttZkQHPqNUGxIn5rn+JLFyTmO1PhdQ0qHxo7DeHbKHtL1pLaZuqPMXpILInYQ5rSJkIuQtIfdKSbuBXf9UNRCqRyRKwcrbXBRo3rpS2YnbFirkEgKc6EQ9pW0vfzM0FZiJbCMuL8tPaxdCOvU1wecPsXfrdV5te0mUxC3BqtcZvDENBOD5eUqTFAo2zFcl2c9zWXljg06YgYDr6z283LFQNv0i65NGn5T12yEPszerBOgq4LenNoY0tDQ/VJ5MsrMs0Wb7eDgVdTgRVJhszC92SxSAEGjzqyHvsmTkEeZBP9LQYzpTbk+7tllnsjDGvAxB69X4vR+Eq7LKSTVtSHj+Pn3V44C9OdZzj39hrQVx/zZyAuFI9XHhA6roIE4zOr/4dPvSd+Gx0ZT2mhhgAbiKftbBAc7OZnOgIKcx/NSJSDXpZnNXIu8XnJiuIq4=
  - secure: S4W6UIQ+FViRdqGDSoQ/oV9ZWIrZ0hkhgOcpEzMhkynQJQjdBlmCk0yUOByk3uB2ddcgO8vZLf4iKOuvxQ6QNmCFXvnr9iur5HMG6BB+DE/6UpsyofrqbYkmionoKCw/QcxVYCYN1vHhYGeX+Ig91fn1IzumEoBmHqrWfR1BxsEvOtnHqnrCxJ3vGVzgw21anqBHjpDgMT4WH5qAnxn+r8X9ofDaE2pbacL6LK+Ze7/iVWnyplYfWlQ3QWkAjSNccgYNxRqA0iamOmJIIg9NBBfv6tIJXC3m8iS4+OBxIpNCZ2sBv4GKQ9KRnhQ8bL5EketB8jkUCgHt2Mnl4K2bbk9vTq+9DW8uyYF/D07oFbr1l8w9NJL/60j1KOrLvbtyTh/g/KA0cd62FywsQ+lg23mBG6YOJ2qYH3AObcJQTVUYIxiVQi/18Hf3kyJKHrdtzm+umHMtMP1Zzl2us3uJilEvFjnLcrx6aIIeiGPNMB3uLx0XXu5upUzQMvQx0VFK4Tx8rBY9IUyIQ9UhHKRFJHMTtXZWDfMQsTjHzjhheCzgnUcI8jf6BLM6CcYAxUzM7mxb5fPh4fuoNr1pqeHJwefkPsdG52k2RqCNk7FRFdtctzFSgHdFk0qtPJbLLKtq1/Th4CcJKLUbS+DDuqCMNjVxnoo2MKA1KEpHJTh/Tbk=
script:
- docker build -f Dockerfile.prod -t "$DOCKER_IMAGE" .
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push "$DOCKER_IMAGE"
