apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-storage-deployment
  labels:
    app: data-storage
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: data-storage
  template:
    metadata:
      labels:
        app: data-storage
    spec:
      containers: 
      - image: leon11sj/data-storage-microservice:version-0.1.0-6.1
        name: data-storage
        command: ["gunicorn"]
        args: ["--bind", "0.0.0.0:5000", "manage:app"]
        env:
        - name: FLASK_ENV
          value: "production"
        - name: APP_SETTINGS
          value: "app.config.ProductionConfig"
        - name: FLASK_APP
          value: app/__init__.py
        - name: BUCKET_NAME
          value: production-bucket598a73db-68f6-4898-b9bb-52cc1abd31d0
        - name: CONFIG_ETCD_HOST_IP
          value: etcd
        - name: CONFIG_ETCD_HOST_PORT
          value: "2379"
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-region
              key: AWS_DEFAULT_REGION
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret-access-key
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-access-key-id
              key: AWS_ACCESS_KEY_ID      
        ports:
        - containerPort: 5000
          name: server
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: data-storage
spec:
  type: ClusterIP
  ports:
  - port: 8082
    protocol: TCP
    targetPort: server
  selector:
    app: data-storage
